export const WORKFLOW_ERROR_CODES = {
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_ACCESS_DENIED: "PROJECT_ACCESS_DENIED",
  PROJECT_ARCHIVED: "PROJECT_ARCHIVED",
  TEAM_ACCESS_DENIED: "TEAM_ACCESS_DENIED",
  ENQUEUE_FAILED: "WORKFLOW_ENQUEUE_FAILED",
  WORKFLOW_JOB_NOT_FOUND: "WORKFLOW_JOB_NOT_FOUND",
  WORKFLOW_JOB_NOT_CANCELLABLE: "WORKFLOW_JOB_NOT_CANCELLABLE",
  WORKFLOW_NODE_NOT_FOUND: "WORKFLOW_NODE_NOT_FOUND",
  WORKFLOW_NODE_INVALID_TRANSITION: "WORKFLOW_NODE_INVALID_TRANSITION",
  WORKFLOW_NODE_NOT_FAILED: "WORKFLOW_NODE_NOT_FAILED",
  WORKFLOW_NODE_NOT_RETRYABLE: "WORKFLOW_NODE_NOT_RETRYABLE",
  WORKFLOW_NODE_NOT_WAITING_APPROVAL: "WORKFLOW_NODE_NOT_WAITING_APPROVAL",
  INTERNAL_ERROR: "WORKFLOW_INTERNAL_ERROR",
} as const;

export type WorkflowErrorCode =
  (typeof WORKFLOW_ERROR_CODES)[keyof typeof WORKFLOW_ERROR_CODES];

export interface WorkflowError {
  code: WorkflowErrorCode;
  message: string;
}

export const WORKFLOW_ERROR_MESSAGES: Record<WorkflowErrorCode, string> = {
  [WORKFLOW_ERROR_CODES.PROJECT_NOT_FOUND]: "项目不存在",
  [WORKFLOW_ERROR_CODES.PROJECT_ACCESS_DENIED]: "无权访问该项目",
  [WORKFLOW_ERROR_CODES.PROJECT_ARCHIVED]: "项目已归档",
  [WORKFLOW_ERROR_CODES.TEAM_ACCESS_DENIED]: "团队权限不足",
  [WORKFLOW_ERROR_CODES.ENQUEUE_FAILED]: "队列投递失败",
  [WORKFLOW_ERROR_CODES.WORKFLOW_JOB_NOT_FOUND]: "工作流任务不存在",
  [WORKFLOW_ERROR_CODES.WORKFLOW_JOB_NOT_CANCELLABLE]: "工作流任务不可取消",
  [WORKFLOW_ERROR_CODES.WORKFLOW_NODE_NOT_FOUND]: "工作流节点不存在",
  [WORKFLOW_ERROR_CODES.WORKFLOW_NODE_INVALID_TRANSITION]: "节点状态流转非法",
  [WORKFLOW_ERROR_CODES.WORKFLOW_NODE_NOT_FAILED]: "节点未失败，不能重试",
  [WORKFLOW_ERROR_CODES.WORKFLOW_NODE_NOT_RETRYABLE]: "节点不可重试",
  [WORKFLOW_ERROR_CODES.WORKFLOW_NODE_NOT_WAITING_APPROVAL]: "节点不在等待确认状态",
  [WORKFLOW_ERROR_CODES.INTERNAL_ERROR]: "任务创建失败",
};

export function workflowError(code: WorkflowErrorCode): WorkflowError {
  return {
    code,
    message: WORKFLOW_ERROR_MESSAGES[code],
  };
}
