export const TTS_ERROR_CODES = {
  VOICE_NOT_FOUND: "VOICE_NOT_FOUND",
  VOICE_LICENSE_NOT_APPROVED: "VOICE_LICENSE_NOT_APPROVED",
  TTS_SCRIPT_TOO_LONG: "TTS_SCRIPT_TOO_LONG",
  TTS_PARAMS_INVALID: "TTS_PARAMS_INVALID",
  TTS_PROVIDER_UNAVAILABLE: "TTS_PROVIDER_UNAVAILABLE",
  TTS_TIMEOUT: "TTS_TIMEOUT",
  TTS_INVALID_AUDIO_OUTPUT: "TTS_INVALID_AUDIO_OUTPUT",
  TTS_REQUEST_NOT_FOUND: "TTS_REQUEST_NOT_FOUND",
  TTS_REQUEST_CREATE_FAILED: "TTS_REQUEST_CREATE_FAILED",
  LEGAL_HIGH_RISK_UNRESOLVED: "LEGAL_HIGH_RISK_UNRESOLVED",
} as const;

export type TtsErrorCode = (typeof TTS_ERROR_CODES)[keyof typeof TTS_ERROR_CODES];

export const TTS_ERROR_MESSAGES: Record<TtsErrorCode, string> = {
  [TTS_ERROR_CODES.VOICE_NOT_FOUND]: "音色不存在",
  [TTS_ERROR_CODES.VOICE_LICENSE_NOT_APPROVED]: "音色未授权",
  [TTS_ERROR_CODES.TTS_SCRIPT_TOO_LONG]: "文案超过 3000 字限制",
  [TTS_ERROR_CODES.TTS_PARAMS_INVALID]: "语音参数不合法",
  [TTS_ERROR_CODES.TTS_PROVIDER_UNAVAILABLE]: "本地 TTS 服务不可用",
  [TTS_ERROR_CODES.TTS_TIMEOUT]: "TTS 服务超时",
  [TTS_ERROR_CODES.TTS_INVALID_AUDIO_OUTPUT]: "TTS 输出音频无效",
  [TTS_ERROR_CODES.TTS_REQUEST_NOT_FOUND]: "TTS 请求不存在",
  [TTS_ERROR_CODES.TTS_REQUEST_CREATE_FAILED]: "TTS 任务创建失败",
  [TTS_ERROR_CODES.LEGAL_HIGH_RISK_UNRESOLVED]: "存在未处理高风险法务项，不能进入声音生成",
};

export const TTS_NODE_TYPE = "tts";
export const TTS_AUDIO_ARTIFACT_TYPE = "audio";
export const TTS_MOCK_PROVIDER = "mock";
export const TTS_LOCAL_PROVIDER = "local";
export const TTS_LOCAL_SYNTHESIZE_PATH = "/synthesize";
export const TTS_LOCAL_TIMEOUT_MS = 30_000;

export const TTS_SPEED_RANGE = {
  min: 0.5,
  max: 2,
  defaultValue: 1,
} as const;

export const TTS_PITCH_RANGE = {
  min: -12,
  max: 12,
  defaultValue: 0,
} as const;

export const TTS_MOCK_SAMPLE_RATE = 16000;
